'use client';

/* eslint-disable jsx-a11y/no-static-element-interactions */
/* eslint-disable jsx-a11y/click-events-have-key-events */
import { useState } from 'react';
import Image from 'next/image';
import { Download, Sparkles, Zap } from 'lucide-react';
import { useTranslations } from 'next-intl';
import Lightbox from 'yet-another-react-lightbox';
import Zoom from 'yet-another-react-lightbox/plugins/zoom';

import 'yet-another-react-lightbox/styles.css';

import { Link } from '@/i18n/navigation';

import { cn } from '@/lib/utils';

import { Button } from '../ui/button';
import HamsterLoading from './HamsterLoading';
import { SITE_ID } from '@/lib/env';

interface HistoryItem {
  id: string;
  prompt: string;
  timestamp: string;
  imageUrl: string;
  isGenerating?: boolean;
}

interface ImageHistoryProps {
  className?: string;
  historyItems?: HistoryItem[];
}

export default function ImageHistory({ className, historyItems = [] }: ImageHistoryProps) {
  const t = useTranslations('components.image-history');
  const [lightboxOpen, setLightboxOpen] = useState(false);
  const [currentImageIndex, setCurrentImageIndex] = useState(0);

  // 过滤出已生成的图片用于预览
  const generatedImages = historyItems.filter((item) => !item.isGenerating && !!item.imageUrl);

  // 构建lightbox slides数据
  const slides = generatedImages.map((item) => ({
    src: item.imageUrl,
    alt: item.prompt,
    title: item.prompt,
    description: item.timestamp,
  }));

  // 处理图片点击
  const handleImageClick = (item: HistoryItem) => {
    if (item.isGenerating || !item.imageUrl) return;

    const imageIndex = generatedImages.findIndex((img) => img.id === item.id);
    if (imageIndex !== -1) {
      setCurrentImageIndex(imageIndex);
      setLightboxOpen(true);
    }
  };

  // 下载带水印的图片
  const handleDownload = async (imageUrl: string, prompt: string) => {
    try {
      // 创建 canvas 和 context
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      // 创建 image 元素
      const img = new window.Image();
      img.crossOrigin = 'anonymous';

      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
        img.src = imageUrl;
      });

      // 设置 canvas 尺寸
      canvas.width = img.width;
      canvas.height = img.height;

      // 绘制原图
      ctx.drawImage(img, 0, 0);

      // 添加水印
      const watermarkText = `Generated by ${SITE_ID}`;
      const fontSize = Math.max(16, Math.min(img.width / 25, 32));

      // 设置字体样式
      ctx.font = `${fontSize}px Arial, sans-serif`;
      ctx.fillStyle = 'rgba(255, 255, 255, 0.8)';
      ctx.strokeStyle = 'rgba(0, 0, 0, 0.5)';
      ctx.lineWidth = 2;
      ctx.textAlign = 'center';

      // 计算水印位置 (底部居中，留出边距)
      const textX = canvas.width / 2;
      const textY = canvas.height - fontSize - 10;

      // 绘制水印 (先描边再填充，产生更好的对比度)
      ctx.strokeText(watermarkText, textX, textY);
      ctx.fillText(watermarkText, textX, textY);

      // 转换为 blob 并下载
      canvas.toBlob(
        (blob) => {
          if (blob) {
            const url = window.URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            link.download = `${prompt.slice(0, 50)}_freeimgen.jpg`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            window.URL.revokeObjectURL(url);
          }
        },
        'image/jpeg',
        0.9,
      );
    } catch (error) {
      console.error('Download failed:', error);
      // 如果水印添加失败，回退到原始下载
      try {
        const response = await fetch(imageUrl);
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${prompt.slice(0, 50)}.jpg`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
      } catch (fallbackError) {
        console.error('Fallback download also failed:', fallbackError);
      }
    }
  };

  return (
    <div className={cn('container-centered', className)}>
      {/* eslint-disable-next-line react/no-unknown-property */}
      <style jsx global>
        {`
          .custom-lightbox .yarl__button:hover {
            background-color: rgba(44, 44, 44, 0.9) !important;
          }
        `}
      </style>
      <div className='rounded-[12px] bg-[#202020] p-[18px]'>
        <div className='flex flex-col gap-[26px]'>
          {/* Free Plan Banner */}
          <div className='rounded-xl bg-[#2c2c2c] p-[18px]'>
            <div className='flex flex-col items-start justify-between gap-4 md:flex-row md:items-center'>
              <div className='flex flex-1 flex-row items-start gap-[9px]'>
                <div className='mt-0.5 h-6 w-6 flex-shrink-0'>
                  <Sparkles className='h-full w-full text-[#B6D4FF]' />
                </div>
                <div className='flex flex-1 flex-col'>
                  <p className='text-[18px] leading-[27px] font-normal tracking-[0.36px] text-[#ffffff]'>
                    {t('free-plan-title')}
                  </p>
                  <p className='text-base font-normal tracking-[0.36px] text-[#b8b8b8]'>{t('free-plan-description')}</p>
                </div>
              </div>
              <a
                rel='nofollow'
                href={process.env.NEXT_PUBLIC_HIGH_QUALITY_LINK}
                className='h-12 flex-shrink-0 rounded-lg bg-[#1677ff] px-8 py-3 text-base font-semibold whitespace-nowrap text-[#ffffff] capitalize backdrop-blur hover:bg-[#1677ff]/90'
              >
                {t('try-now')}
              </a>
            </div>
          </div>

          {/* History Items */}
          {historyItems.map((item) => (
            <div key={item.id} className='flex flex-col gap-3'>
              {/* Header */}
              <div className='flex flex-col justify-between gap-2 md:flex-row md:items-center'>
                <div className='flex min-w-0 flex-1 flex-row items-center gap-3'>
                  <span className='text-[18px] leading-[27px] font-normal tracking-[0.36px] whitespace-nowrap text-[#ffffff]'>
                    {t('generate-label')}
                  </span>
                  <p className='line-clamp-1 flex-1 overflow-hidden text-base font-normal tracking-[0.36px] break-words text-ellipsis text-[#b8b8b8]'>
                    {item.prompt}
                  </p>
                </div>
                <span className='text-base font-normal tracking-[0.36px] whitespace-nowrap text-[#b8b8b8] md:ml-3'>
                  {item.timestamp}
                </span>
              </div>

              {/* Tips */}
              <div className='flex flex-row items-center gap-3'>
                <span className='text-[18px] leading-[27px] font-normal tracking-[0.36px] whitespace-nowrap text-[#ffffff]'>
                  {t('tips-label')}
                </span>
                <span className='text-base font-normal text-[#b8b8b8]'>{t('tips-message')}</span>
              </div>

              {/* Image Container */}
              {item.isGenerating ? (
                /* Generating State */
                <div className='flex h-[330px] w-full max-w-[640px] items-center justify-center rounded-xl bg-[#2c2c2c] md:h-[480px]'>
                  <div className='flex flex-col items-center gap-3'>
                    {/* Mouse Animation Placeholder - you mentioned you'll handle this */}
                    <HamsterLoading />
                    <p className='text-center text-[18px] leading-[27px] font-normal tracking-[0.36px] text-[#ffffff]'>
                      {t('estimated-time')}
                    </p>
                    <Link
                      rel='nofollow'
                      href={process.env.NEXT_PUBLIC_HIGH_QUALITY_LINK!}
                      className='flex h-[52px] w-full items-center justify-center gap-2 rounded-lg bg-[#1677ff] px-8 py-3 backdrop-blur hover:bg-[#1677ff]/90'
                    >
                      <Zap className='h-6 w-6 text-white' />
                      <span className='text-[16px] leading-[24px] font-semibold text-[#ffffff] capitalize'>
                        {t('generate-faster')}
                      </span>
                    </Link>
                  </div>
                </div>
              ) : (
                /* Generated Image */
                <div className='h-[280px] w-auto md:h-[480px]'>
                  <Image
                    src={item.imageUrl}
                    alt={t('image-alt')}
                    className='h-full w-auto cursor-pointer rounded-xl object-contain transition-opacity hover:opacity-90'
                    width={720}
                    height={480}
                    onClick={() => handleImageClick(item)}
                  />
                </div>
              )}
            </div>
          ))}

          {historyItems.length === 0 && (
            <div className='flex h-[240px] items-center justify-center rounded-2xl bg-[#2c2c2c] md:h-[320px]'>
              <div className='text-[16px] text-[#b8b8b8]'>{t('no-data')}</div>
            </div>
          )}
        </div>
      </div>

      {/* Lightbox */}
      <Lightbox
        className='custom-lightbox'
        open={lightboxOpen}
        close={() => setLightboxOpen(false)}
        index={currentImageIndex}
        slides={slides}
        carousel={{ finite: slides.length <= 1 }}
        render={{
          buttonPrev: slides.length <= 1 ? () => null : undefined,
          buttonNext: slides.length <= 1 ? () => null : undefined,
          buttonZoom: () => null,
        }}
        toolbar={{
          buttons: [
            <Link
              key='get-higher-quality'
              rel='nofollow'
              className='font-noto-sans rounded-lg bg-[#1677ff] pt-3 pr-8 pb-3 pl-8 text-center text-base font-semibold text-white capitalize hover:bg-[#1677ff]/90'
              href={process.env.NEXT_PUBLIC_HIGH_QUALITY_LINK!}
            >
              {t('get-higher-quality')}
            </Link>,
            <Button
              className='h-12 cursor-pointer bg-[#2C2C2C] px-0 py-0 text-white hover:bg-[#2C2C2C]/90 hover:text-white'
              key='download'
              onClick={() => handleDownload(slides[currentImageIndex].src, slides[currentImageIndex].title || 'image')}
            >
              <Download className='size-6 shrink-0' />
            </Button>,
            'close',
          ],
        }}
        styles={{
          container: { backgroundColor: 'rgba(0, 0, 0, 0.9)' },
          toolbar: {
            background: 'transparent',
            padding: '16px',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            gap: '8px',
          },
          button: {
            backgroundColor: '#2C2C2C',
            color: '#ffffff',
            backdropFilter: 'blur(8px)',
            border: 'none',
            borderRadius: '8px',
            width: '48px',
            height: '48px',
            transition: 'background-color 0.2s',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            cursor: 'pointer',
          },
          navigationNext: {
            right: '16px',
          },
          navigationPrev: {
            left: '16px',
          },
          icon: {
            width: '24px',
            height: '24px',
            flexShrink: 0,
          },
        }}
        plugins={[Zoom]}
        animation={{ zoom: 500 }}
        zoom={{
          maxZoomPixelRatio: 10,
          zoomInMultiplier: 1,
          doubleClickMaxStops: 2,
          keyboardMoveDistance: 50,
          wheelZoomDistanceFactor: 100,
          pinchZoomDistanceFactor: 100,
          scrollToZoom: false,
        }}
        controller={{
          closeOnBackdropClick: true,
          closeOnPullDown: true,
          closeOnPullUp: true,
        }}
      />
    </div>
  );
}
