'use client';

import React, { useState } from 'react';
import { useTranslations } from 'next-intl';
import Lightbox from 'yet-another-react-lightbox';
import Zoom from 'yet-another-react-lightbox/plugins/zoom';

import 'yet-another-react-lightbox/styles.css';

import { Link } from '@/i18n/navigation';
import { Download } from 'lucide-react';

import { scaleWithPica } from '@/lib/utils/imageUtils';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

import { Button } from '../ui/button';

interface ImageLightboxProps {
  images: Array<{
    src: string;
    alt?: string;
    width?: number;
    height?: number;
  }>;
  open: boolean;
  onClose: () => void;
  currentIndex: number;
  onIndexChange?: (index: number) => void;
  enableWatermark?: boolean; // 控制是否添加水印
}

type ImageFormat = 'jpg' | 'webp' | 'png';
type ImageScale = '1x' | '2x' | '4x';

const ImageLightbox: React.FC<ImageLightboxProps> = ({
  images,
  open,
  onClose,
  currentIndex,
  onIndexChange,
  enableWatermark = true,
}) => {
  const t = useTranslations('components.light-box');
  const [selectedFormat, setSelectedFormat] = useState<ImageFormat>('jpg');
  const [selectedScale, setSelectedScale] = useState<ImageScale>('1x');

  const handleDownload = async () => {
    if (!images[currentIndex]) return;
    try {
      const currentImage = images[currentIndex];
      let downloadUrl = currentImage.src;

      // Scale image if needed
      if (selectedScale !== '1x') {
        const scaleMultiplier = selectedScale === '2x' ? 2 : 4;
        downloadUrl = await scaleWithPica(currentImage.src, scaleMultiplier);
      }

      // Handle format conversion and download
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d')!;
      const img = new Image();

      img.crossOrigin = 'anonymous';
      img.onload = () => {
        canvas.width = img.naturalWidth;
        canvas.height = img.naturalHeight;

        // Enable high-quality rendering
        ctx.imageSmoothingEnabled = true;
        ctx.imageSmoothingQuality = 'high';

        // Draw image
        ctx.drawImage(img, 0, 0);

        // Add watermark if enabled
        if (enableWatermark) {
          const fontSize = Math.max(16, Math.min(canvas.width, canvas.height) * 0.03);
          ctx.font = `${fontSize}px Arial`;
          ctx.fillStyle = 'rgba(255, 255, 255, 0.7)';
          ctx.textAlign = 'right';
          ctx.fillText('Generated by grokimagegenerator.com', canvas.width - 20, canvas.height - 20);
        }

        // Convert to desired format
        const mimeType =
          selectedFormat === 'jpg' ? 'image/jpeg' : selectedFormat === 'png' ? 'image/png' : 'image/webp';

        canvas.toBlob(
          (blob) => {
            if (blob) {
              const url = URL.createObjectURL(blob);
              const a = document.createElement('a');
              a.href = url;
              a.download = `grokimagegenerator_${Date.now()}.${selectedFormat}`;
              document.body.appendChild(a);
              a.click();
              document.body.removeChild(a);
              URL.revokeObjectURL(url);
            }
          },
          mimeType,
          selectedFormat === 'jpg' ? 0.98 : 1,
        );
      };

      img.onerror = () => {
        // Fallback: direct download
        const a = document.createElement('a');
        a.href = downloadUrl;
        a.download = `grokimagegenerator_${Date.now()}.${selectedFormat}`;
        a.target = '_blank';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
      };

      img.src = downloadUrl;
    } catch (error) {
      console.error('Download failed:', error);
    }
  };

  return (
    <>
      {/* eslint-disable-next-line react/no-unknown-property */}
      <style jsx global>
        {`
          .custom-lightbox .yarl__button:hover {
            background-color: rgba(44, 44, 44, 0.9) !important;
          }
        `}
      </style>
      <Lightbox
        className='custom-lightbox'
        open={open}
        close={onClose}
        slides={images}
        index={currentIndex}
        plugins={[Zoom]}
        animation={{ zoom: 500 }}
        zoom={{
          maxZoomPixelRatio: 3,
          zoomInMultiplier: 2,
          doubleTapDelay: 300,
          doubleClickDelay: 300,
          doubleClickMaxStops: 2,
          keyboardMoveDistance: 50,
          wheelZoomDistanceFactor: 100,
          pinchZoomDistanceFactor: 100,
          scrollToZoom: true,
        }}
        carousel={{ finite: images.length <= 1 }}
        controller={{
          closeOnPullDown: true,
          closeOnBackdropClick: true,
        }}
        render={{
          buttonPrev: images.length <= 1 ? () => null : undefined,
          buttonNext: images.length <= 1 ? () => null : undefined,
          buttonZoom: () => null, // We're using custom download
        }}
        on={{
          view: ({ index }) => onIndexChange?.(index),
        }}
        toolbar={{
          buttons: [
            <Link
              key='get-higher-quality'
              rel='nofollow'
              className='box-border flex h-12 shrink-0 items-center justify-center rounded-lg bg-[#1677ff] px-8 py-3 text-[16px] font-semibold text-white capitalize backdrop-blur backdrop-filter transition-colors hover:bg-[#1677ff]/90'
              href={process.env.NEXT_PUBLIC_HIGH_QUALITY_LINK || '/'}
            >
              {t('get-higher-quality')}
            </Link>,
            <Link
              key='image-to-video'
              rel='nofollow'
              href={process.env.NEXT_PUBLIC_AI_VIDEO_LINK || '/'}
              className='box-border flex h-12 shrink-0 items-center justify-center rounded-[7px] bg-white px-7 py-[10.5px] text-[14px] font-semibold text-[#1677ff] capitalize backdrop-blur-[7px] backdrop-filter transition-colors hover:bg-gray-50'
            >
              {t('image-to-video')}
            </Link>,
            <div key='bottom-toolbar' className='h-12 rounded-lg border border-white/10 bg-[#2c2c2c]'>
              <div className='box-border flex h-12 flex-row items-center justify-center gap-[3px] p-1'>
                <Select value={selectedFormat} onValueChange={(value) => setSelectedFormat(value as ImageFormat)}>
                  <SelectTrigger className='flex h-full min-w-[80px] shrink-0 flex-row items-center justify-start gap-1 rounded border-0 bg-white/10 py-1 pr-1 pl-2 text-[16px] text-white/70'>
                    <SelectValue placeholder='Format' />
                  </SelectTrigger>
                  <SelectContent className='z-[10000] border-white/10 bg-[#2c2c2c]'>
                    <SelectItem
                      value='jpg'
                      className='text-white/70 focus:bg-white/10 focus:text-white/70 dark:hover:bg-white/10'
                    >
                      JPG
                    </SelectItem>
                    <SelectItem
                      value='webp'
                      className='text-white/70 focus:bg-white/10 focus:text-white/70 dark:hover:bg-white/10'
                    >
                      WEBP
                    </SelectItem>
                    <SelectItem
                      value='png'
                      className='text-white/70 focus:bg-white/10 focus:text-white/70 dark:hover:bg-white/10'
                    >
                      PNG
                    </SelectItem>
                  </SelectContent>
                </Select>
                <Select value={selectedScale} onValueChange={(value) => setSelectedScale(value as ImageScale)}>
                  <SelectTrigger className='flex h-full min-w-[60px] shrink-0 flex-row items-center justify-start gap-1 rounded border-0 bg-white/10 py-1 pr-1 pl-2 text-[16px] text-white/70'>
                    <SelectValue placeholder='Scale' />
                  </SelectTrigger>
                  <SelectContent className='z-[10000] border-white/10 bg-[#2c2c2c]'>
                    <SelectItem
                      value='1x'
                      className='text-white/70 focus:bg-white/10 focus:text-white/70 dark:hover:bg-white/10'
                    >
                      1X
                    </SelectItem>
                    <SelectItem
                      value='2x'
                      className='text-white/70 focus:bg-white/10 focus:text-white/70 dark:hover:bg-white/10'
                    >
                      2X
                    </SelectItem>
                    <SelectItem
                      value='4x'
                      className='text-white/70 focus:bg-white/10 focus:text-white/70 dark:hover:bg-white/10'
                    >
                      4X
                    </SelectItem>
                  </SelectContent>
                </Select>
                <Button
                  className='bg-input/30 flex h-full w-10 shrink-0 items-center justify-center rounded border-0 p-0 text-white/70 transition-colors hover:bg-white/20'
                  onClick={handleDownload}
                >
                  <Download className='size-5 shrink-0' />
                </Button>
              </div>
            </div>,
            'close',
          ],
        }}
        styles={{
          container: { backgroundColor: 'rgba(0, 0, 0, 0.9)' },
          toolbar: {
            background: 'transparent',
            padding: '16px',
            display: 'flex',
            justifyContent: 'flex-end',
            alignItems: 'center',
            gap: '8px',
            width: '100%',
            flexWrap: 'wrap',
          },
          button: {
            backgroundColor: '#2C2C2C',
            color: '#ffffff',
            backdropFilter: 'blur(8px)',
            border: 'none',
            borderRadius: '8px',
            width: '48px',
            height: '48px',
            transition: 'background-color 0.2s',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            cursor: 'pointer',
          },
          navigationNext: {
            right: '16px',
          },
          navigationPrev: {
            left: '16px',
          },
          icon: {
            width: '24px',
            height: '24px',
            flexShrink: 0,
          },
        }}
      />
    </>
  );
};

export default ImageLightbox;
