export const MOCK_GENERATION_IMAGE = {
  id: '1789219896394592257',
  createTime: '2024-05-11 17:03:59',
  platformType: 23,
  prompt: 'in the style of Neo-Traditional, with a tattoo of a cross',
  costCredits: 20,
  title: 'in the style of Neo-Traditional',
  url: 'https://img.artiversehub.ai/2024/05/11/c13cad9b4a6f4d7d9a5351591bf2253a.png',
  resolution: '512x512',
  thumbnailUrl: 'https://img.artiversehub.ai/2024/05/11/8e1f0835b3a84af2a85e066021a3f1f8.png',
  modelName: 'yomico-art-tattoo',
  nickName: 'Graham Quan',
};

export const MOCK_IMAGE_LIST = [
  {
    categoryId: 4,
    categoryName: 'Category 1',
    costCredits: 72,
    createBy: 447,
    createTime: '2024-05-09T06:22:31.995Z',
    id: 1,
    mimeType: 'image/jpeg',
    modelId: 70,
    modelName: 'Model 1',
    negativePrompt: 'Negative prompt for Image 1',
    nickName: 'Creator 1',
    params: { key: { subKey: 'value' } },
    platformName: 'AI Platform',
    platformType: 3,
    prompt: 'Prompt for Image 1',
    resolution: '1920x1080',
    size: 598648,
    tags: 'Tag1,Tag2,Tag3',
    thumbnailUrl: '/images/modals/anime angel girl.png',
    title: 'Image 1',
    updateBy: 457,
    updateTime: '2024-05-09T06:22:31.995Z',
    url: '/images/modals/anime angel girl.png',
  },
  {
    categoryId: 9,
    categoryName: 'Category 2',
    costCredits: 70,
    createBy: 507,
    createTime: '2024-05-09T06:22:31.996Z',
    id: 2,
    mimeType: 'image/jpeg',
    modelId: 84,
    modelName: 'Model 2',
    negativePrompt: 'Negative prompt for Image 2',
    nickName: 'Creator 2',
    params: { key: { subKey: 'value' } },
    platformName: 'AI Platform',
    platformType: 3,
    prompt: 'Prompt for Image 2',
    resolution: '1920x1080',
    size: 972265,
    tags: 'Tag1,Tag2,Tag3',
    thumbnailUrl: '/images/modals/anime angel girl.png',
    title: 'Image 2',
    updateBy: 37,
    updateTime: '2024-05-09T06:22:31.996Z',
    url: '/images/modals/anime angel girl.png',
  },
  {
    categoryId: 8,
    categoryName: 'Category 3',
    costCredits: 52,
    createBy: 772,
    createTime: '2024-05-09T06:22:31.996Z',
    id: 3,
    mimeType: 'image/jpeg',
    modelId: 31,
    modelName: 'Model 3',
    negativePrompt: 'Negative prompt for Image 3',
    nickName: 'Creator 3',
    params: { key: { subKey: 'value' } },
    platformName: 'AI Platform',
    platformType: 2,
    prompt: 'Prompt for Image 3',
    resolution: '1920x1080',
    size: 451199,
    tags: 'Tag1,Tag2,Tag3',
    thumbnailUrl: '/images/modals/anime angel girl.png',
    title: 'Image 3',
    updateBy: 896,
    updateTime: '2024-05-09T06:22:31.996Z',
    url: '/images/modals/anime angel girl.png',
  },
  {
    categoryId: 2,
    categoryName: 'Category 4',
    costCredits: 75,
    createBy: 853,
    createTime: '2024-05-09T06:22:31.996Z',
    id: 4,
    mimeType: 'image/jpeg',
    modelId: 11,
    modelName: 'Model 4',
    negativePrompt: 'Negative prompt for Image 4',
    nickName: 'Creator 4',
    params: { key: { subKey: 'value' } },
    platformName: 'AI Platform',
    platformType: 1,
    prompt: 'Prompt for Image 4',
    resolution: '1920x1080',
    size: 893464,
    tags: 'Tag1,Tag2,Tag3',
    thumbnailUrl: '/images/modals/anime angel girl.png',
    title: 'Image 4',
    updateBy: 103,
    updateTime: '2024-05-09T06:22:31.996Z',
    url: '/images/modals/anime angel girl.png',
  },
  {
    categoryId: 1,
    categoryName: 'Category 5',
    costCredits: 44,
    createBy: 381,
    createTime: '2024-05-09T06:22:31.996Z',
    id: 5,
    mimeType: 'image/jpeg',
    modelId: 18,
    modelName: 'Model 5',
    negativePrompt: 'Negative prompt for Image 5',
    nickName: 'Creator 5',
    params: { key: { subKey: 'value' } },
    platformName: 'AI Platform',
    platformType: 3,
    prompt: 'Prompt for Image 5',
    resolution: '1920x1080',
    size: 418791,
    tags: 'Tag1,Tag2,Tag3',
    thumbnailUrl: '/images/modals/anime angel girl.png',
    title: 'Image 5',
    updateBy: 276,
    updateTime: '2024-05-09T06:22:31.996Z',
    url: '/images/modals/anime angel girl.png',
  },
  {
    categoryId: 6,
    categoryName: 'Category 6',
    costCredits: 19,
    createBy: 956,
    createTime: '2024-05-09T06:22:31.996Z',
    id: 6,
    mimeType: 'image/jpeg',
    modelId: 29,
    modelName: 'Model 6',
    negativePrompt: 'Negative prompt for Image 6',
    nickName: 'Creator 6',
    params: { key: { subKey: 'value' } },
    platformName: 'AI Platform',
    platformType: 2,
    prompt: 'Prompt for Image 6',
    resolution: '1920x1080',
    size: 779654,
    tags: 'Tag1,Tag2,Tag3',
    thumbnailUrl: '/images/modals/anime angel girl.png',
    title: 'Image 6',
    updateBy: 341,
    updateTime: '2024-05-09T06:22:31.996Z',
    url: '/images/modals/anime angel girl.png',
  },
  {
    categoryId: 6,
    categoryName: 'Category 7',
    costCredits: 39,
    createBy: 850,
    createTime: '2024-05-09T06:22:31.996Z',
    id: 7,
    mimeType: 'image/jpeg',
    modelId: 27,
    modelName: 'Model 7',
    negativePrompt: 'Negative prompt for Image 7',
    nickName: 'Creator 7',
    params: { key: { subKey: 'value' } },
    platformName: 'AI Platform',
    platformType: 2,
    prompt: 'Prompt for Image 7',
    resolution: '1920x1080',
    size: 520625,
    tags: 'Tag1,Tag2,Tag3',
    thumbnailUrl: '/images/modals/anime angel girl.png',
    title: 'Image 7',
    updateBy: 305,
    updateTime: '2024-05-09T06:22:31.996Z',
    url: '/images/modals/anime angel girl.png',
  },
  {
    categoryId: 9,
    categoryName: 'Category 8',
    costCredits: 65,
    createBy: 393,
    createTime: '2024-05-09T06:22:31.996Z',
    id: 8,
    mimeType: 'image/jpeg',
    modelId: 52,
    modelName: 'Model 8',
    negativePrompt: 'Negative prompt for Image 8',
    nickName: 'Creator 8',
    params: { key: { subKey: 'value' } },
    platformName: 'AI Platform',
    platformType: 1,
    prompt: 'Prompt for Image 8',
    resolution: '1920x1080',
    size: 183667,
    tags: 'Tag1,Tag2,Tag3',
    thumbnailUrl: '/images/modals/anime angel girl.png',
    title: 'Image 8',
    updateBy: 527,
    updateTime: '2024-05-09T06:22:31.996Z',
    url: '/images/modals/anime angel girl.png',
  },
  {
    categoryId: 10,
    categoryName: 'Category 9',
    costCredits: 71,
    createBy: 844,
    createTime: '2024-05-09T06:22:31.996Z',
    id: 9,
    mimeType: 'image/jpeg',
    modelId: 33,
    modelName: 'Model 9',
    negativePrompt: 'Negative prompt for Image 9',
    nickName: 'Creator 9',
    params: { key: { subKey: 'value' } },
    platformName: 'AI Platform',
    platformType: 1,
    prompt: 'Prompt for Image 9',
    resolution: '1920x1080',
    size: 437253,
    tags: 'Tag1,Tag2,Tag3',
    thumbnailUrl: '/images/modals/anime angel girl.png',
    title: 'Image 9',
    updateBy: 71,
    updateTime: '2024-05-09T06:22:31.996Z',
    url: '/images/modals/anime angel girl.png',
  },
  {
    categoryId: 1,
    categoryName: 'Category 10',
    costCredits: 3,
    createBy: 384,
    createTime: '2024-05-09T06:22:31.996Z',
    id: 10,
    mimeType: 'image/jpeg',
    modelId: 5,
    modelName: 'Model 10',
    negativePrompt: 'Negative prompt for Image 10',
    nickName: 'Creator 10',
    params: { key: { subKey: 'value' } },
    platformName: 'AI Platform',
    platformType: 3,
    prompt: 'Prompt for Image 10',
    resolution: '1920x1080',
    size: 341125,
    tags: 'Tag1,Tag2,Tag3',
    thumbnailUrl: '/images/modals/anime angel girl.png',
    title: 'Image 10',
    updateBy: 791,
    updateTime: '2024-05-09T06:22:31.996Z',
    url: '/images/modals/anime angel girl.png',
  },
];

export const homeNavCards = [
  {
    id: '1',
    img: 'https://via.placeholder.com/150',
    name: 'Home Home Home Home Home Home HomeHome Home',
    link: 'https://example.com/home',
    content:
      'Welcome to the homepage. Here you will find the latest updates, featured articles, and a quick overview of what our website has to offer. Stay tuned for more exciting content and updates.',
  },
  {
    id: '2',
    img: '',
    name: 'About',
    link: 'https://example.com/about',
    content:
      'Learn more about us. Our company has been at the forefront of innovation, providing top-notch services and products to our valued customers. Our team is dedicated to delivering excellence in every aspect of our business.',
  },
  {
    id: '3',
    img: 'https://via.placeholder.com/150',
    name: 'Services',
    link: 'https://example.com/services',
    content:
      'Discover our services. We offer a wide range of solutions tailored to meet the unique needs of our clients. From consulting to implementation, our experts are here to help you achieve your goals with our comprehensive service offerings.',
  },
  {
    id: '4',
    img: 'https://via.placeholder.com/150',
    name: 'Contact',
    link: 'https://example.com/contact',
    content:
      'Get in touch with us. Whether you have questions, feedback, or need assistance, our team is here to help. Contact us through our various channels, and we will get back to you as soon as possible.',
  },
  {
    id: '5',
    img: 'https://via.placeholder.com/150',
    name: 'Blog',
    link: 'https://example.com/blog',
    content:
      'Read our latest posts. Our blog features insights, tips, and stories from industry experts. Stay informed with our in-depth articles on a variety of topics, and join the conversation by sharing your thoughts and comments.',
  },
  {
    id: '6',
    img: 'https://via.placeholder.com/150',
    name: 'Careers',
    link: 'https://example.com/careers',
    content:
      'Join our team. We are always looking for talented and passionate individuals to join our growing company. Explore our current job openings, learn about our culture, and find out how you can become a part of our dynamic team.',
  },
  {
    id: '7',
    img: 'https://via.placeholder.com/150',
    name: 'Portfolio',
    link: 'https://example.com/portfolio',
    content:
      'View our work. Our portfolio showcases a selection of our best projects, highlighting our expertise and creativity. Browse through our case studies and see how we have helped our clients achieve success.',
  },
  {
    id: '8',
    img: 'https://via.placeholder.com/150',
    name: 'Testimonials',
    link: 'https://example.com/testimonials',
    content:
      'See what our clients say. We take pride in the positive feedback we receive from our clients. Read their testimonials and learn about their experiences working with us. Their success stories are a testament to our commitment to excellence.',
  },
  {
    id: '9',
    img: 'https://via.placeholder.com/150',
    name: 'FAQ',
    link: 'https://example.com/faq',
    content:
      'Frequently asked questions. Find answers to the most common questions about our products and services. Our FAQ section is designed to provide you with quick and easy access to important information.',
  },
  {
    id: '10',
    img: 'https://via.placeholder.com/150',
    name: 'Privacy Policy',
    link: 'https://example.com/privacy',
    content:
      'Read our privacy policy. Your privacy is important to us. Our privacy policy outlines how we collect, use, and protect your personal information. We are committed to ensuring your data is safe and secure.',
  },
  {
    id: '11',
    img: 'https://via.placeholder.com/150',
    name: 'Terms of Service',
    link: 'https://example.com/terms',
    content:
      'Review our terms of service. Our terms of service provide detailed information about the rules and regulations for using our website and services. Please read them carefully to understand your rights and responsibilities.',
  },
  {
    id: '12',
    img: 'https://via.placeholder.com/150',
    name: 'Support',
    link: 'https://example.com/support',
    content:
      'Get support for our products. Our support team is here to help you with any issues or questions you may have. Explore our support resources, including guides, tutorials, and contact information, to get the assistance you need.',
  },
];
